# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.api.gestione_credenziali_api import GestioneCredenzialiApi


class TestGestioneCredenzialiApi(unittest.TestCase):
    """GestioneCredenzialiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GestioneCredenzialiApi()

    def tearDown(self) -> None:
        pass

    def test_credentials_boarding_qrcode_token_get(self) -> None:
        """Test case for credentials_boarding_qrcode_token_get

        Informazioni boarding
        """
        pass

    def test_credentials_credentials_id_change_pin_put(self) -> None:
        """Test case for credentials_credentials_id_change_pin_put

        Cambio PIN
        """
        pass

    def test_credentials_credentials_id_delete(self) -> None:
        """Test case for credentials_credentials_id_delete

        Elimina credenziali
        """
        pass

    def test_credentials_credentials_id_get(self) -> None:
        """Test case for credentials_credentials_id_get

        Dettaglio credenziali
        """
        pass

    def test_credentials_credentials_id_reset_pin_put(self) -> None:
        """Test case for credentials_credentials_id_reset_pin_put

        Reset PIN
        """
        pass

    def test_credentials_credentials_id_rimuovi_associazione_delete(self) -> None:
        """Test case for credentials_credentials_id_rimuovi_associazione_delete

        Rimuovi associazione credenziali
        """
        pass

    def test_credentials_credentials_id_status_get(self) -> None:
        """Test case for credentials_credentials_id_status_get

        Stato credenziali
        """
        pass


if __name__ == '__main__':
    unittest.main()
