# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_ca.models.credentials_authorize_request import CredentialsAuthorizeRequest  # noqa: E501

class TestCredentialsAuthorizeRequest(unittest.TestCase):
    """CredentialsAuthorizeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CredentialsAuthorizeRequest:
        """Test CredentialsAuthorizeRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CredentialsAuthorizeRequest`
        """
        model = CredentialsAuthorizeRequest()  # noqa: E501
        if include_optional:
            return CredentialsAuthorizeRequest(
                credentials_id = '012345678',
                num_signatures = 56,
                hashes = [
                    ''
                    ],
                hash_algo = '2.16.840.1.101.3.4.2.10',
                description = '',
                auth_data = [
                    rentri_ca.models.auth_object_data.AuthObjectData(
                        id = 'moBILE0', 
                        value = '', )
                    ],
                client_data = ''
            )
        else:
            return CredentialsAuthorizeRequest(
                credentials_id = '012345678',
                num_signatures = 56,
                hashes = [
                    ''
                    ],
                hash_algo = '2.16.840.1.101.3.4.2.10',
                auth_data = [
                    rentri_ca.models.auth_object_data.AuthObjectData(
                        id = 'moBILE0', 
                        value = '', )
                    ],
        )
        """

    def testCredentialsAuthorizeRequest(self):
        """Test CredentialsAuthorizeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
