# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.models.push_notification_device import PushNotificationDevice

class TestPushNotificationDevice(unittest.TestCase):
    """PushNotificationDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PushNotificationDevice:
        """Test PushNotificationDevice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PushNotificationDevice`
        """
        model = PushNotificationDevice()
        if include_optional:
            return PushNotificationDevice(
                identifier = '0',
                notification_callback_uri = '0',
                notification_callback_parameters = {
                    'key' : ''
                    }
            )
        else:
            return PushNotificationDevice(
                identifier = '0',
                notification_callback_uri = '0',
                notification_callback_parameters = {
                    'key' : ''
                    },
        )
        """

    def testPushNotificationDevice(self):
        """Test PushNotificationDevice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
