# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_ca.models.auth_mode import AuthMode  # noqa: E501

class TestAuthMode(unittest.TestCase):
    """AuthMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthMode(self):
        """Test AuthMode"""
        # inst = AuthMode()

if __name__ == '__main__':
    unittest.main()
