# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_ca.models.signature_qualifier import SignatureQualifier  # noqa: E501

class TestSignatureQualifier(unittest.TestCase):
    """SignatureQualifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignatureQualifier(self):
        """Test SignatureQualifier"""
        # inst = SignatureQualifier()

if __name__ == '__main__':
    unittest.main()
