# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.models.auth_object_data import AuthObjectData

class TestAuthObjectData(unittest.TestCase):
    """AuthObjectData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthObjectData:
        """Test AuthObjectData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthObjectData`
        """
        model = AuthObjectData()
        if include_optional:
            return AuthObjectData(
                id = ERROR_TO_EXAMPLE_VALUE,
                value = ''
            )
        else:
            return AuthObjectData(
                id = ERROR_TO_EXAMPLE_VALUE,
        )
        """

    def testAuthObjectData(self):
        """Test AuthObjectData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
