# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.models.push_notification_type import PushNotificationType

class TestPushNotificationType(unittest.TestCase):
    """PushNotificationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPushNotificationType(self):
        """Test PushNotificationType"""
        # inst = PushNotificationType()

if __name__ == '__main__':
    unittest.main()
