# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.api.gestione_dispositivi_api import GestioneDispositiviApi


class TestGestioneDispositiviApi(unittest.TestCase):
    """GestioneDispositiviApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GestioneDispositiviApi()

    def tearDown(self) -> None:
        pass

    def test_devices_device_id_identificativo_soggetto_get(self) -> None:
        """Test case for devices_device_id_identificativo_soggetto_get

        Dettaglio dispositivo
        """
        pass

    def test_devices_get(self) -> None:
        """Test case for devices_get

        Elenco dispositivi
        """
        pass

    def test_devices_sync_put(self) -> None:
        """Test case for devices_sync_put

        Sincronizza dispositivo
        """
        pass


if __name__ == '__main__':
    unittest.main()
