# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.models.create_update_credentials_request import CreateUpdateCredentialsRequest

class TestCreateUpdateCredentialsRequest(unittest.TestCase):
    """CreateUpdateCredentialsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUpdateCredentialsRequest:
        """Test CreateUpdateCredentialsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUpdateCredentialsRequest`
        """
        model = CreateUpdateCredentialsRequest()
        if include_optional:
            return CreateUpdateCredentialsRequest(
                identificativo_soggetto = '0',
                num_iscr_sito = '0123456789101112131415161718192021',
                identificativo = '0',
                identificativo_altro = '',
                user_name = '',
                device_info = rentri_ca.models.device_info.DeviceInfo(
                    identifier = '0', 
                    model = '0', 
                    manufacturer = '0', 
                    name = '0', 
                    os_version = '0', 
                    form_factor = '0', 
                    type = null, 
                    platform = '0', 
                    notification_callback_uri = '0', 
                    notification_callback_parameters = {
                        'key' : ''
                        }, ),
                app_info = rentri_ca.models.app_info.AppInfo(
                    name = '0', 
                    package_name = '0', 
                    version = '0', 
                    build = '0', )
            )
        else:
            return CreateUpdateCredentialsRequest(
                identificativo_soggetto = '0',
                identificativo = '0',
                device_info = rentri_ca.models.device_info.DeviceInfo(
                    identifier = '0', 
                    model = '0', 
                    manufacturer = '0', 
                    name = '0', 
                    os_version = '0', 
                    form_factor = '0', 
                    type = null, 
                    platform = '0', 
                    notification_callback_uri = '0', 
                    notification_callback_parameters = {
                        'key' : ''
                        }, ),
                app_info = rentri_ca.models.app_info.AppInfo(
                    name = '0', 
                    package_name = '0', 
                    version = '0', 
                    build = '0', ),
        )
        """

    def testCreateUpdateCredentialsRequest(self):
        """Test CreateUpdateCredentialsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
