# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.models.signature_request import SignatureRequest

class TestSignatureRequest(unittest.TestCase):
    """SignatureRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignatureRequest:
        """Test SignatureRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignatureRequest`
        """
        model = SignatureRequest()
        if include_optional:
            return SignatureRequest(
                credentials_id = '012345678',
                sad = '0',
                hashes = [
                    ''
                    ],
                hash_algo = '2.16.840.1.101.3.4.2.1',
                sign_algo = '1.2.840.10045.4.3.20',
                sign_algo_params = '',
                client_data = ''
            )
        else:
            return SignatureRequest(
                credentials_id = '012345678',
                sad = '0',
                hashes = [
                    ''
                    ],
                sign_algo = '1.2.840.10045.4.3.20',
        )
        """

    def testSignatureRequest(self):
        """Test SignatureRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
