# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_ca.models.device_model import DeviceModel  # noqa: E501

class TestDeviceModel(unittest.TestCase):
    """DeviceModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceModel:
        """Test DeviceModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceModel`
        """
        model = DeviceModel()  # noqa: E501
        if include_optional:
            return DeviceModel(
                identifier = '',
                name = '',
                model = '',
                manufacturer = '',
                os_version = '',
                form_factor = '',
                type = 'Physical',
                platform = '',
                data_registrazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_banned = True,
                stato = 'Attivo',
                app_name = '',
                app_package_name = '',
                app_version = '',
                app_build = '',
                notification_callback_uri = '',
                notification_callback_parameters = {
                    'key' : ''
                    },
                siti = [
                    ''
                    ]
            )
        else:
            return DeviceModel(
        )
        """

    def testDeviceModel(self):
        """Test DeviceModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
