# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.models.stato import Stato

class TestStato(unittest.TestCase):
    """Stato unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStato(self):
        """Test Stato"""
        # inst = Stato()

if __name__ == '__main__':
    unittest.main()
