# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_ca.models.reset_pin_request import ResetPinRequest  # noqa: E501

class TestResetPinRequest(unittest.TestCase):
    """ResetPinRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResetPinRequest:
        """Test ResetPinRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResetPinRequest`
        """
        model = ResetPinRequest()  # noqa: E501
        if include_optional:
            return ResetPinRequest(
                token = '',
                new_pin = '012345',
                abort = True
            )
        else:
            return ResetPinRequest(
                token = '',
        )
        """

    def testResetPinRequest(self):
        """Test ResetPinRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
