# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.models.app_info import AppInfo

class TestAppInfo(unittest.TestCase):
    """AppInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppInfo:
        """Test AppInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppInfo`
        """
        model = AppInfo()
        if include_optional:
            return AppInfo(
                name = '0',
                package_name = '0',
                version = '0',
                build = '0'
            )
        else:
            return AppInfo(
                name = '0',
                package_name = '0',
                version = '0',
                build = '0',
        )
        """

    def testAppInfo(self):
        """Test AppInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
