# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_ca.models.key_status import KeyStatus  # noqa: E501

class TestKeyStatus(unittest.TestCase):
    """KeyStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyStatus(self):
        """Test KeyStatus"""
        # inst = KeyStatus()

if __name__ == '__main__':
    unittest.main()
