# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.models.credentials_list_response import CredentialsListResponse

class TestCredentialsListResponse(unittest.TestCase):
    """CredentialsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CredentialsListResponse:
        """Test CredentialsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CredentialsListResponse`
        """
        model = CredentialsListResponse()
        if include_optional:
            return CredentialsListResponse(
                credentials_ids = [
                    ''
                    ],
                credentials_infos = [
                    rentri_ca.models.credentials_info.CredentialsInfo(
                        credentials_id = '', 
                        description = '', 
                        signature_qualifier = null, 
                        key = null, 
                        cert = null, 
                        auth = null, 
                        scal = '', 
                        multisign = 56, 
                        lang = '', )
                    ],
                only_valid = True
            )
        else:
            return CredentialsListResponse(
        )
        """

    def testCredentialsListResponse(self):
        """Test CredentialsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
