# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.api.ca_api import CAApi


class TestCAApi(unittest.TestCase):
    """CAApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CAApi()

    def tearDown(self) -> None:
        pass

    def test_ca_num_seriale_ca_cert_crl_get(self) -> None:
        """Test case for ca_num_seriale_ca_cert_crl_get

        CRL
        """
        pass

    def test_ca_num_seriale_ca_cert_get(self) -> None:
        """Test case for ca_num_seriale_ca_cert_get

        Certificato CA
        """
        pass


if __name__ == '__main__':
    unittest.main()
