# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_ca.models.sync_device_info_request import SyncDeviceInfoRequest  # noqa: E501

class TestSyncDeviceInfoRequest(unittest.TestCase):
    """SyncDeviceInfoRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncDeviceInfoRequest:
        """Test SyncDeviceInfoRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncDeviceInfoRequest`
        """
        model = SyncDeviceInfoRequest()  # noqa: E501
        if include_optional:
            return SyncDeviceInfoRequest(
                identifier = '0',
                name = '0',
                os_version = '0',
                notification_callback_uri = '0',
                notification_callback_parameters = {
                    'key' : ''
                    },
                app_info = rentri_ca.models.app_info.AppInfo(
                    name = '0', 
                    package_name = '0', 
                    version = '0', 
                    build = '0', )
            )
        else:
            return SyncDeviceInfoRequest(
                identifier = '0',
                name = '0',
                os_version = '0',
                notification_callback_uri = '0',
                notification_callback_parameters = {
                    'key' : ''
                    },
        )
        """

    def testSyncDeviceInfoRequest(self):
        """Test SyncDeviceInfoRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
