# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_ca.models.info_data import InfoData  # noqa: E501

class TestInfoData(unittest.TestCase):
    """InfoData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InfoData:
        """Test InfoData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InfoData`
        """
        model = InfoData()  # noqa: E501
        if include_optional:
            return InfoData(
                specs = '',
                name = '',
                logo = '',
                region = '',
                lang = '',
                description = '',
                auth_type = [
                    ''
                    ],
                oauth2 = '',
                methods = [
                    ''
                    ],
                sign_algorithms = rentri_ca.models.sign_algorithms.SignAlgorithms(
                    algos = [
                        ''
                        ], 
                    algo_params = [
                        ''
                        ], ),
                signature_formats = rentri_ca.models.signature_formats.SignatureFormats(
                    formats = [
                        ''
                        ], 
                    envelope_properties = [
                        [
                            ''
                            ]
                        ], ),
                conformance_levels = [
                    ''
                    ]
            )
        else:
            return InfoData(
        )
        """

    def testInfoData(self):
        """Test InfoData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
