# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.models.credentials_status_response import CredentialsStatusResponse

class TestCredentialsStatusResponse(unittest.TestCase):
    """CredentialsStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CredentialsStatusResponse:
        """Test CredentialsStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CredentialsStatusResponse`
        """
        model = CredentialsStatusResponse()
        if include_optional:
            return CredentialsStatusResponse(
                identifier = '',
                identificativo = '',
                identificativo_altro = '',
                user_name = '',
                pin = '',
                stato = 'Attivo',
                siti = [
                    rentri_ca.models.credentials_sito.CredentialsSito(
                        num_iscr_sito = '', 
                        nome = '', 
                        indirizzo = '', 
                        civico = '', 
                        comune_id = '', 
                        provincia_id = '', )
                    ],
                is_abbinato_solo_soggetto = True
            )
        else:
            return CredentialsStatusResponse(
        )
        """

    def testCredentialsStatusResponse(self):
        """Test CredentialsStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
