# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_ca.models.create_update_credentials_response import CreateUpdateCredentialsResponse

class TestCreateUpdateCredentialsResponse(unittest.TestCase):
    """CreateUpdateCredentialsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUpdateCredentialsResponse:
        """Test CreateUpdateCredentialsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUpdateCredentialsResponse`
        """
        model = CreateUpdateCredentialsResponse()
        if include_optional:
            return CreateUpdateCredentialsResponse(
                credentials_id = '',
                pin = ''
            )
        else:
            return CreateUpdateCredentialsResponse(
        )
        """

    def testCreateUpdateCredentialsResponse(self):
        """Test CreateUpdateCredentialsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
