# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, constr

class AppInfo(BaseModel):
    """
    Informazioni sulla App.  # noqa: E501
    """
    name: constr(strict=True, max_length=50, min_length=1) = Field(default=..., description="Nome dell'applicazione.")
    package_name: constr(strict=True, max_length=100, min_length=1) = Field(default=..., description="Nome del package o identificativo dell'applicazione.")
    version: constr(strict=True, max_length=14, min_length=1) = Field(default=..., description="Versione dell'applicazione.")
    build: constr(strict=True, max_length=14, min_length=1) = Field(default=..., description="Numero della build della versione dell'applicazione.")
    __properties = ["name", "package_name", "version", "build"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AppInfo:
        """Create an instance of AppInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AppInfo:
        """Create an instance of AppInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AppInfo.parse_obj(obj)

        _obj = AppInfo.parse_obj({
            "name": obj.get("name"),
            "package_name": obj.get("package_name"),
            "version": obj.get("version"),
            "build": obj.get("build")
        })
        return _obj


