# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, constr

class ChangePinRequest(BaseModel):
    """
    ChangePinRequest
    """
    current_pin: constr(strict=True, max_length=6, min_length=6) = Field(default=..., description="PIN corrente.")
    new_pin: constr(strict=True, max_length=6, min_length=6) = Field(default=..., description="Nuovo PIN.")
    __properties = ["current_pin", "new_pin"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ChangePinRequest:
        """Create an instance of ChangePinRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ChangePinRequest:
        """Create an instance of ChangePinRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ChangePinRequest.parse_obj(obj)

        _obj = ChangePinRequest.parse_obj({
            "current_pin": obj.get("current_pin"),
            "new_pin": obj.get("new_pin")
        })
        return _obj


