# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class CreateUpdateCredentialsResponse(BaseModel):
    """
    CreateUpdateCredentialsResponse
    """
    credentials_id: Optional[StrictStr] = Field(default=None, description="Identificativo delle credenziali.")
    pin: Optional[StrictStr] = Field(default=None, description="PIN.")
    __properties = ["credentials_id", "pin"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateUpdateCredentialsResponse:
        """Create an instance of CreateUpdateCredentialsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if credentials_id (nullable) is None
        # and __fields_set__ contains the field
        if self.credentials_id is None and "credentials_id" in self.__fields_set__:
            _dict['credentials_id'] = None

        # set to None if pin (nullable) is None
        # and __fields_set__ contains the field
        if self.pin is None and "pin" in self.__fields_set__:
            _dict['pin'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateUpdateCredentialsResponse:
        """Create an instance of CreateUpdateCredentialsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateUpdateCredentialsResponse.parse_obj(obj)

        _obj = CreateUpdateCredentialsResponse.parse_obj({
            "credentials_id": obj.get("credentials_id"),
            "pin": obj.get("pin")
        })
        return _obj


