# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from rentri_ca.models.auth_data import AuthData
from rentri_ca.models.cert_data import CertData
from rentri_ca.models.key_data import KeyData
from rentri_ca.models.signature_qualifier import SignatureQualifier
from typing import Optional, Set
from typing_extensions import Self

class CredentialsInfoResponse(BaseModel):
    """
    CredentialsInfoResponse
    """ # noqa: E501
    description: Optional[StrictStr] = Field(default=None, description="Descrizione delle credenziali.")
    signature_qualifier: Optional[SignatureQualifier] = Field(default=None, description="Identificativo che qualifica il tipo di firma per cui sono adatte le credenziali.")
    key: Optional[KeyData] = Field(default=None, description="Informazioni sulla chiave di firma.")
    cert: Optional[CertData] = Field(default=None, description="Informazioni sul certificato.")
    auth: Optional[AuthData] = Field(default=None, description="Informazioni sulla modalità di autorizzazione.")
    scal: Optional[StrictStr] = Field(default=None, description="Indica se il servizio di autorizzazione genera un Signature Activation Data (SAD) che contiene un collegamento con i codici hash da firmare. 1 - non collegato (default) 2 - collegato")
    multisign: Optional[StrictInt] = Field(default=None, description="Numero massimo di firme che possono essere create con queste credenziali con una singola richiesta.")
    lang: Optional[StrictStr] = Field(default=None, description="Lingua prescelta per la risposta, specificata secondo RFC 5646.")
    __properties: ClassVar[List[str]] = ["description", "signature_qualifier", "key", "cert", "auth", "scal", "multisign", "lang"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CredentialsInfoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of key
        if self.key:
            _dict['key'] = self.key.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cert
        if self.cert:
            _dict['cert'] = self.cert.to_dict()
        # override the default output from pydantic by calling `to_dict()` of auth
        if self.auth:
            _dict['auth'] = self.auth.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if signature_qualifier (nullable) is None
        # and model_fields_set contains the field
        if self.signature_qualifier is None and "signature_qualifier" in self.model_fields_set:
            _dict['signature_qualifier'] = None

        # set to None if key (nullable) is None
        # and model_fields_set contains the field
        if self.key is None and "key" in self.model_fields_set:
            _dict['key'] = None

        # set to None if cert (nullable) is None
        # and model_fields_set contains the field
        if self.cert is None and "cert" in self.model_fields_set:
            _dict['cert'] = None

        # set to None if auth (nullable) is None
        # and model_fields_set contains the field
        if self.auth is None and "auth" in self.model_fields_set:
            _dict['auth'] = None

        # set to None if scal (nullable) is None
        # and model_fields_set contains the field
        if self.scal is None and "scal" in self.model_fields_set:
            _dict['scal'] = None

        # set to None if multisign (nullable) is None
        # and model_fields_set contains the field
        if self.multisign is None and "multisign" in self.model_fields_set:
            _dict['multisign'] = None

        # set to None if lang (nullable) is None
        # and model_fields_set contains the field
        if self.lang is None and "lang" in self.model_fields_set:
            _dict['lang'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CredentialsInfoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "signature_qualifier": obj.get("signature_qualifier"),
            "key": KeyData.from_dict(obj["key"]) if obj.get("key") is not None else None,
            "cert": CertData.from_dict(obj["cert"]) if obj.get("cert") is not None else None,
            "auth": AuthData.from_dict(obj["auth"]) if obj.get("auth") is not None else None,
            "scal": obj.get("scal"),
            "multisign": obj.get("multisign"),
            "lang": obj.get("lang")
        })
        return _obj


