# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class DeviceType(str, Enum):
    """
    DeviceType
    """

    """
    allowed enum values
    """
    PHYSICAL = 'Physical'
    VIRTUAL = 'Virtual'

    @classmethod
    def from_json(cls, json_str: str) -> DeviceType:
        """Create an instance of DeviceType from a JSON string"""
        return DeviceType(json.loads(json_str))


