# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field
from rentri_ca.models.push_notification_device import PushNotificationDevice
from rentri_ca.models.push_notification_type import PushNotificationType

class PushNotificationDeviceSync(BaseModel):
    """
    PushNotificationDeviceSync
    """
    type: Optional[PushNotificationType] = None
    device: PushNotificationDevice = Field(...)
    __properties = ["type", "device"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PushNotificationDeviceSync:
        """Create an instance of PushNotificationDeviceSync from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "type",
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of device
        if self.device:
            _dict['device'] = self.device.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PushNotificationDeviceSync:
        """Create an instance of PushNotificationDeviceSync from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PushNotificationDeviceSync.parse_obj(obj)

        _obj = PushNotificationDeviceSync.parse_obj({
            "type": obj.get("type"),
            "device": PushNotificationDevice.from_dict(obj.get("device")) if obj.get("device") is not None else None
        })
        return _obj


