# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PushNotificationType(str, Enum):
    """
    PushNotificationType
    """

    """
    allowed enum values
    """
    NOTIFICATION = 'Notification'
    DEVICEINFO = 'DeviceInfo'
    DEVICESYNC = 'DeviceSync'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PushNotificationType from a JSON string"""
        return cls(json.loads(json_str))


