# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, constr

class ResetPinRequest(BaseModel):
    """
    ResetPinRequest
    """
    token: StrictStr = Field(default=..., description="Token della richiesta di reset.")
    new_pin: Optional[constr(strict=True, max_length=6, min_length=6)] = Field(default=None, description="Nuovo PIN.")
    abort: Optional[StrictBool] = Field(default=None, description="Annullamento della procedura.")
    __properties = ["token", "new_pin", "abort"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ResetPinRequest:
        """Create an instance of ResetPinRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if new_pin (nullable) is None
        # and __fields_set__ contains the field
        if self.new_pin is None and "new_pin" in self.__fields_set__:
            _dict['new_pin'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ResetPinRequest:
        """Create an instance of ResetPinRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ResetPinRequest.parse_obj(obj)

        _obj = ResetPinRequest.parse_obj({
            "token": obj.get("token"),
            "new_pin": obj.get("new_pin"),
            "abort": obj.get("abort")
        })
        return _obj


