# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SignatureQualifier(str, Enum):
    """
    SignatureQualifier
    """

    """
    allowed enum values
    """
    EU_E_IDAS_QES = 'EU_eIDAS_QES'
    EU_E_IDAS_AES = 'EU_eIDAS_AES'
    EU_E_IDAS_AESQC = 'EU_eIDAS_AESQC'
    EU_E_IDAS_QE_SEAL = 'EU_eIDAS_QESeal'
    EU_E_IDAS_AE_SEAL = 'EU_eIDAS_AESeal'
    EU_E_IDAS_AE_SEAL_QC = 'EU_eIDAS_AESealQC'
    ZA_ECTA_AES = 'ZA_ECTA_AES'
    ZA_ECTA_OES = 'ZA_ECTA_OES'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SignatureQualifier from a JSON string"""
        return cls(json.loads(json_str))


