# coding: utf-8

"""
    ca-rentri

    Servizio RENTRI CA

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Stato(str, Enum):
    """
    Stato
    """

    """
    allowed enum values
    """
    ATTIVO = 'Attivo'
    ELIMINATO = 'Eliminato'
    NUOVO = 'Nuovo'
    REVOCATO = 'Revocato'
    SCADUTO = 'Scaduto'

    @classmethod
    def from_json(cls, json_str: str) -> Stato:
        """Create an instance of Stato from a JSON string"""
        return Stato(json.loads(json_str))


